# Generated by Django 4.2.4 on 2023-08-10 04:08

import autoslug.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
                ('slug', autoslug.fields.AutoSlugField(editable=False, max_length=100, null=True, populate_from='video_title', unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Work',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=1500)),
                ('description', models.TextField()),
                ('project_link', models.CharField(max_length=2000)),
                ('code_link', models.CharField(max_length=2000)),
                ('image', models.ImageField(upload_to='images')),
                ('tag', models.ManyToManyField(to='portfolio.tag')),
            ],
        ),
    ]
