# Generated by Django 4.2.4 on 2023-08-10 04:33

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_tag_work'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='slug',
            field=autoslug.fields.AutoSlugField(editable=False, max_length=100, null=True, populate_from='title', unique=True),
        ),
    ]
