# Generated by Django 4.2.4 on 2023-08-11 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0005_skill'),
    ]

    operations = [
        migrations.AddField(
            model_name='skill',
            name='bg_color',
            field=models.CharField(default='#edf2f8', max_length=200),
        ),
    ]
