# Generated by Django 4.2.4 on 2023-08-12 06:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0006_skill_bg_color'),
    ]

    operations = [
        migrations.CreateModel(
            name='Year',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
                ('company', models.CharField(max_length=500)),
                ('description', models.CharField(max_length=1000)),
                ('year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portfolio.year')),
            ],
        ),
    ]
